name: Compile & Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed
  repository_dispatch:
    types: [pages-deploy]

permissions:
  contents: write

jobs:
  deploy:
    if: >-
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success') ||
      github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from workflow_run
        if: github.event_name == 'workflow_run'
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Checkout code
        if: github.event_name == 'repository_dispatch'
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Install TypeScript
        run: npm install -g typescript
      - name: Compile TypeScript
        run: tsc
      - name: Temporarily Modify .gitignore
        run: sed -i '/dist\//d' .gitignore
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
