name: Scheduled Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 0,3,6,9,12,15,18,21 * * *'
    - cron: '30 1,4,7,10,13,16,19,22 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger pages deploy
        uses: saedyousef/repository-dispatch@v0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          event_type: pages-deploy
